package main

import (
	"fmt"
	"github.com/phith0n/zkar"
	"github.com/sanity-io/litter"
	"io/ioutil"
	"regexp"
)

func main() {
	var filename = "testcases/ysoserial/URLDNS.ser"
	// var filename = "example/object.poc"
	data, err := ioutil.ReadFile(filename)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	ser, err := zkar.FromBytes(data)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	sq := litter.Options{
		StripPackageNames: false,
		HidePrivateFields: true,
		FieldExclusions:   regexp.MustCompile(`^(XXX_.*)$`), // XXX_ is a prefix of fields generated by protoc-gen-go
		Separator:         " ",
		HideZeroValues: true,
	}
	sq.Dump(ser)
	// ioutil.WriteFile("testcases/ysoserial/C3P01.ser", ser.ToBytes(), fs.FileMode(755))
	// fmt.Println(ser.ToString())
}
