package class

type AttrAccessFlag uint16

const (
	AttrAccPublic       AttrAccessFlag = 0x0001 // Declared public; may be accessed from outside its package.
	AttrAccPrivate      AttrAccessFlag = 0x0002 // Declared private; accessible only within the defining class and other classes belonging to the same nest (§5.4.4).
	AttrAccProtected    AttrAccessFlag = 0x0004 // Declared protected; may be accessed within subclasses.
	AttrAccStatic       AttrAccessFlag = 0x0008 // Declared static.
	AttrAccFinal        AttrAccessFlag = 0x0010 // Declared final; must not be overridden (§5.4.5).
	AttrAccSynchronized AttrAccessFlag = 0x0020 // Declared synchronized; invocation is wrapped by a monitor use.
	AttrAccBridge       AttrAccessFlag = 0x0040 // A bridge method, generated by the compiler.
	AttrAccVarargs      AttrAccessFlag = 0x0080 // Declared with variable number of arguments.
	AttrAccNative       AttrAccessFlag = 0x0100 // Declared native; implemented in a language other than the Java programming language.
	AttrAccAbstract     AttrAccessFlag = 0x0400 // Declared abstract; no implementation is provided.
	AttrAccStrict       AttrAccessFlag = 0x0800 // In a class file whose major version number is at least 46 and at most 60: Declared strictfp.
	AttrAccSynthetic    AttrAccessFlag = 0x1000 // Declared synthetic; not present in the source code.
)

func (aaf AttrAccessFlag) HasAccessFlag(flag AttrAccessFlag) bool {
	return (flag & aaf) == flag
}
